AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  FunctionName:
    Type: String
    Default: eks-lambda-drainer
  FunctionRoleArn:
    Type: String
    Default: ""

Transform: AWS::Serverless-2016-10-31
Description: eks-lambda-drainer Func
Resources:
  Func:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        # serverless app from all regoins should be able to import this ApplicationId from 'us-east-1' across accounts.
        ApplicationId: arn:aws:serverlessrepo:us-east-1:903779448426:applications/eks-lambda-drainer
        SemanticVersion: 1.0.1-beta2
      Parameters:
        # ClusterName: !Ref ClusterName
        FunctionName: !Ref FunctionName
        FunctionRoleArn: !Ref FunctionRoleArn

Outputs:
  Func:
    Description: "Lambda function Arn"
    Value: !GetAtt Func.Outputs.FuncArn
  FuncIamRole:
    Description: "Lambda function IAM role Arn"
    Value: !GetAtt Func.Outputs.FuncIamRole

